# Generated by Django 3.1.11 on 2021-06-21 18:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail_footnotes.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtail_footnotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footnote',
            options={'verbose_name': 'Translatable Footnote'},
        ),
        migrations.AddField(
            model_name='footnote',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='footnote',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='footnote',
            name='uuid',
            field=wagtail_footnotes.fields.CustomUUIDField(help_text='The ID of the footnote is shown in the rich text editor for reference.', verbose_name='ID'),
        ),
    ]
