# Generated by Django 3.1.11 on 2021-06-21 18:22

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_footnotes", "0002_footnote_bootstrap_migration"),
    ]

    operations = [
        BootstrapTranslatableModel("wagtail_footnotes.Footnote"),
    ]
