# Generated by Django 3.1.11 on 2021-06-21 18:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtail_footnotes', '0003_footnote_bootstrap_migration_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footnote',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='footnote',
            unique_together={('translation_key', 'locale')},
        ),
    ]
