# Generated by Django 4.1.13 on 2024-01-16 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("wagtail_footnotes", "0004_footnote_translatable_mixin_migration"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="footnote",
            unique_together={("translation_key", "locale"), ("page", "uuid")},
        ),
    ]
